name = "RegressionFormulae"
uuid = "545c379f-4ec2-4339-9aea-38f2fb6a8ba2"
authors = ["Dave Kleinschmidt", "Phillip Alday"]
version = "0.1.2"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[compat]
Combinatorics = "1"
StatsBase = "0.33"
StatsModels = "0.7"
julia = "1.6"

[extras]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["StatsBase", "StatsModels", "Test"]
